### ISSUE TITLE
Error while due to space in reaction id

### ISSUE THREAD

**Issue by MaaikeRemeijer** [cnapy-org/CNApy#487] opened 2023-11-09 11:33 UTC
Hi, 

When making a toy model I accidentally put a space in a reaction id and after removing it I still cannot save my project. 
I get the following error:

`Traceback (most recent call last): File "C:\Users\mre283\Anaconda3\envs\cnapy-1.1.6\lib\site-packages\optlang\container.py", line 82, in __getitem__ return self._object_list[item] # Try treating item as int or slice TypeError: list indices must be integers or slices, not str During handling of the above exception, another exception occurred: Traceback (most recent call last): File "C:\Users\mre283\Anaconda3\envs\cnapy-1.1.6\lib\site-packages\cnapy\gui_elements\main_window.py", line 1344, in save_project self.continue_save_project() File "C:\Users\mre283\Anaconda3\envs\cnapy-1.1.6\lib\site-packages\cnapy\gui_elements\main_window.py", line 1354, in continue_save_project self.save_sbml(tmp_dir + "model.sbml") File "C:\Users\mre283\Anaconda3\envs\cnapy-1.1.6\lib\site-packages\cnapy\gui_elements\main_window.py", line 1315, in save_sbml cobra.io.write_sbml_model( File "C:\Users\mre283\Anaconda3\envs\cnapy-1.1.6\lib\site-packages\cobra\io\sbml.py", line 1174, in write_sbml_model doc = _model_to_sbml(cobra_model, f_replace=f_replace, **kwargs) File "C:\Users\mre283\Anaconda3\envs\cnapy-1.1.6\lib\site-packages\cobra\io\sbml.py", line 1360, in _model_to_sbml reaction_coefficients = linear_reaction_coefficients(cobra_model) File "C:\Users\mre283\Anaconda3\envs\cnapy-1.1.6\lib\site-packages\cobra\util\solver.py", line 100, in linear_reaction_coefficients forward_coefficient = coefficients.get(rxn.forward_variable, 0) File "C:\Users\mre283\Anaconda3\envs\cnapy-1.1.6\lib\site-packages\cobra\core\reaction.py", line 190, in forward_variable return self.model.variables[self.id] File "C:\Users\mre283\Anaconda3\envs\cnapy-1.1.6\lib\site-packages\optlang\container.py", line 84, in __getitem__ return self._dict[item] # Treat item as key (name) KeyError: 'NAD de' `

I get the same error when I try to export to SBML to save my progress. 

Is there any way to fix this?

**Comment by Paulocracy** [comment] 2023-11-10 13:40
Closing as duplicate of #488 (if this is not a duplicate, please notify us, e.g. by commenting here)

**Closed by Paulocracy** 2023-11-10 13:40 UTC
Labels: bug

**Comment by MaaikeRemeijer** [comment] 2023-11-10 13:41
I see, I don't know how I forgot that I already opened an issue, sorry!
