### ISSUE TITLE
Unable to install from CNApy installer

### ISSUE THREAD

**Issue by CrimsonCurlew** [cnapy-org/CNApy#386] opened 2022-06-27 22:50 UTC
Hello, thank you for developing this!
I'm struggling to get the cnapy installer to work, I would prefer it as a standalone, and have tried the 1.0.9 version installer and it didn't work at all going into program files. I tried another time with an earlier version 1.0.8 (I think) into a hard drive file (just incase admin rights were the issue) - there it managed to download minianaconda, but not cna itself, before the installer window came up that it had successful installed, which seems to be timed. Is there a way of installing from the master file downloaded as a zip file? It maybe I have slow internet, and the connection isn't open long enough for it to be fully installed from the installer.

I have tried installing/ through anaconda from zipfile, but I'm not that confident coding; and I would prefer a standalone programme if possible.

Best wishes

**Comment by sthiele** [comment] 2022-06-30 07:43
Thanks @CrimsonCurlew  for reporting this issue.

@Paulocracy maybe you could have a look at this issue? :pray: 
Looks like the latest version of CNApy switched to a new windows installer :+1: 

I guess there are two things:

- 1st The installer should not report a successful install if it could not install properly.

- 2nd can we provide a stand alone installer for offline installation?
The aim of [constructor](https://github.com/conda/constructor) is to build such stand alone installers.
Of course our old constructor based installer also needed an internet connection to pull the dependencies, which was also because some dependencies where not available on conda. But there has been some updates on the repositories since then ... so maybe it would worth checking again if it is possible to create a standalone installer? 
Of such an installer would be huge :fearful:

**Comment by Paulocracy** [comment] 2022-07-07 08:25
Hello!

First of all sorry for my late reply, I've been sick for quite a long time :-|

It's right that the installer was changed starting with 1.0.8 because the old constructor-based installer just stopped working. The new installer itself is also open source and its source code can be found [here](https://github.com/cnapy-org/CNApy-installer).

@CrimsonCurlew The CNApy installer version for CNApy 1.0.8 is not up-to-date and might have more quirks than the new installer which is attached to CNApy 1.0.9. Therefore, I would suggest to retry the installer for CNApy 1.0.9. Alternatively, if this installer still doesn't want to work on your device and without having to set-up Python and git, you can try to install CNApy directly with Miniconda as described [here](https://github.com/cnapy-org/CNApy/blob/master/README.md#install-cnapy-with-conda).
For the installer of 1.0.9, I'd like to know if you get a specific error message in the installation process? It's true that the installer doesn't work if you select a folder which needs admin rights, therefore it is recommended to select a folder which doesn't need these rights. Additionally, the speed of your internet connection should not play any role in the success of the installation.
I'm also, as suggested by @sthiele, looking after whether an offline installer for CNApy is feasible.

**Comment by CrimsonCurlew** [comment] 2022-07-20 13:48
Hello!

No worries, thank you for getting back. It might have been partially where I was installing it: in the programme files (where I should have admin rights)- 'An error occurred in a download process of the installation. Please make sure your internet connection works and retry the installation', I tried again downloading onto a external disk hard drive (as I am working on a laptop) and got 'Error whilst running installation process unknown error during the execution of the installation process. Please make sure you have access permissions on the selected installation folder' (it only downloaded the miniconda installer), so I decieded to try again in the documents folder ...as admin rights shouldn't be an issue - there it seemed to work, a black box with text came up, and it installed a desktop icon. However now when I click onto the desktop item, it doesn't work.

All three times it came up with a successful install message.

I shall have a look at the instructions for installing with Miniconda.... The final time; there were some warning messages about dependances for miniconda that came up very quickly, (too quickly to note down) I feel like it is almost there...

**Comment by Paulocracy** [comment] 2022-07-21 09:12
Hello again!

Thank you for sharing your further experiences :-) Thanks to that, I found a bug in the CNApy installer which caused it to show a "successful installation" message even if it wasn't successful :3 This should be fixed now. Furthermore, regarding your issue with the program files folder, I added a user-privilege-granting procedure to the installer right at the start of it.
You may download and try this new installer, just the old version, from the latest CNApy release 1.0.9.
I hope that it doesn't include the bug where CNApy is installed and shown at the desktop with a dysfunctional link, but fortunately a colleague of mine has the same problem and I'm trying to reproduce it with his help.

Regarding the Miniconda installation, dependency warnings are normal as long as they do not cause the installation process to stop. Did you follow the instructions of CNApy's README and if so, at which point does the Miniconda installation seem to fail?

**Comment by CrimsonCurlew** [comment] 2022-07-21 10:06
Hello, I go it working following Miniconda instructions! So all good - it just didn't seem to work from miniconda when it was through the windows exe opening it up. I think the difference was when minconda opened after the windows exe, it downloaded less of the required dependancies, and following the miniconda instructions it downloaded more... unfortunately, I couldn't tell you the exact difference. Thank you for the help!

**Comment by Paulocracy** [comment] 2022-07-21 11:16
Hello! It's great to hear that you could successfully install CNApy :D I'll try to find out more about the remaining .exe installer problem with my colleague. In the meantime, I wish you much success with using CNApy and if you encounter any problem, feel free to open new issues here :-)

**Closed by Paulocracy** 2022-07-21 11:16 UTC
Labels: enhancement
